### ISSUE TITLE
Update preview gif in readme

### ISSUE THREAD

**Issue by dancormier** [dancormier/react-native-swipeout#21]

**Comment by bdougie** [comment]
I am just getting into this library but when you or someone else get's to this it would would be nice if the readme example matched the gif example.

I am following along but don't understand how the following
```js
// Buttons
var swipeoutBtns = [
  {
    text: 'Button'
  }
]
```
renders:

![image](https://cloud.githubusercontent.com/assets/5713670/11533970/3d90713e-98c1-11e5-8bb7-c0a647a48f39.png)

I am still digging into how this works, but thought I would mention it since its a current pain point. I did the following

```js
var swipeBtns = [{
  delete: 'Delete',
}];
```
and it renders:

<img width="443" alt="screenshot 2015-12-02 06 48 39" src="https://cloud.githubusercontent.com/assets/5713670/11533999/6ef14226-98c1-11e5-95d5-a5d003f981c1.png">


Looking forward to assisting you with this project in the future and keep up the great work.

**Comment by bdougie** [comment]
Of course as soon as I submit this, I figured it out

```
// switching the key to text fix it.

var swipeBtns = [{
  text: 'Delete',
}];
```

**Comment by dancormier** [comment]
Good suggestion :+1: I'm happy to hear you figured it out.

I will implement it in my next major release, which I'm working on in the branch [dc-redux](https://github.com/dancormier/react-native-swipeout/tree/dc-redux).
