### ISSUE TITLE
Swipe-out in ListViews

### ISSUE THREAD

**Issue by tazmattaz** [dancormier/react-native-swipeout#24]
Hello, 
I am using this plugin and really this is very good. Really good work. :+1: 

I am trying to use this into ListViews. I am facing below issues:
1. If we try to open swipe-out bar then first should be closed if open
2. There should be provision to check if swipe-out bar is closed or not ?

**Comment by dancormier** [comment]
Hey @tazmattaz,
I'm happy you are finding the plugin useful. I might have a solution to your problems.

1. I would suggest viewing the wiki [entry for closing swipeouts](https://github.com/dancormier/react-native-swipeout/wiki/Closing-Swipeouts).
2. I didn't see a need to check if bar is closed, since that would return true on all but 1 element, so instead I chose to check for "onOpen". This will return which swipeout is open while the user is opening it. Essentially, I think this is providing you with the functionality you describe (just in reverse).
